name: Secrets and Variables

on:
  workflow_dispatch:

env:
  workflowVar: TestWorkflowVar

jobs:
  job:
    runs-on: ubuntu-latest
    
    env:
      jobVar: TestJobVar
      
    steps:
      - name: Print secrets and variables
        shell: bash
        env:
          mySecret: ${{ secrets.repoSecret }}
          myVariable: ${{ vars.repoVar }}
          stepVar: TestStepVar
        run: |
          echo Repo secret: $mySecret
          echo Manually echoing the secret: Dette er hemmelig
          
          if [ "$mySecret" = "Dette er hemmelig" ]; then
              echo "We know the secret"
          else
              echo "Unknown seceet"
          fi

          echo Repo variable: $myVariable
          echo Workflow variable: $workflowVar
          echo Job variable: $jobVar
          echo Step variable: $stepVar
